DROP TABLE IF EXISTS PLANT;

DROP SEQUENCE IF EXISTS SEQGEN19;

-- Create sequences for autoincrement fields

CREATE SEQUENCE SEQGEN19
    START WITH 10
	INCREMENT BY 1
	NO MAXVALUE
	NO MINVALUE
	CACHE 1
;

-- Create tables

CREATE TABLE PLANT (
  plant_id INT DEFAULT SEQGEN19.NEXTVAL PRIMARY KEY,
  year INT NOT NULL,
  pstatabb VARCHAR(500) NOT NULL,
  pname VARCHAR(500) NOT NULL,
  genid VARCHAR(500) NOT NULL,
  genstat VARCHAR(500) NOT NULL,
  genntan INT
);
